travis:
  secure:
    BINSTAR_TOKEN: dOaoI6wxPXpoIHZdTjj6ZS6aspl5vEqBzCj0PUeH5ZeqFGGyFrEIYoXPbnDLr6h6bInm4uPI8wrmjw4liauhas304ZG02mkUUPBsVZ0ee48IyUpmp4ibMkV2rjjRregWfnzB6JfssjF9Bn8uftKx4PvJ3E7Ru74lHEBREbvaWreyDVrH4C7ax3e9B5+qKTAdnRVVSk0I21zDDGZbbX4ZjTsT9ppltEu1Xq3AJ7NDwnCsFnD6/3aafPOt/mSQUXnJrMzzLfF6h0Hz7qrSAGT3ommMi59uxVA2FWMvs/gzhWZlfpjGBJbzM3jt3n4VHnMYepzIevY51HWrUOFmXWGfL4YAnr/wvmEPDvhZ1DDNwH7PsT6c4o+pSNYu73cBYRQfbJFgquIHcNbVcl0Vr/9amYzAg2dK9Z9OwET5XU/CLuUaPyyC0TRUz27758UO0ptpV32N1B+tuRfl98zsLfPb9uvLtUogWhjVsQWbVcEohMEKBtPcdZksaEpiyQjB0armG9r+assbVzl/bcbpJc5E4TpG4wZfyihgZSXs30VSQetsmkJf1SD1asytmAbRTKUo6EXNUNYjRORrba5BwXlWqgXyj6iCyeeTMvTWLWP6AeOztzXIzhnsdTO0jCbSJOdrfHCx90hD8EvYK+1Fiw0YNzhd9pHOqtda6iiK3Lwrov0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
